name: Deploy to BigDevSoon

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to BigDevSoon
        run: |
          # Replace the following command with your actual deployment command
          echo "Deploying to BigDevSoon..."
        env:
          YOUR_SECRET_KEY: ${{ secrets.YOUR_SECRET_KEY }}
